[package]
name = "gedcom"
version = "0.1.0"
authors = ["Robert Pirtle <astropirtle@gmail.com>"]
edition = "2018"
include = ["Cargo.toml", "src/**/*.rs"]

[dependencies]

[lib]
name = "gedcom"
path = "src/lib.rs"

[[bin]]
name = "parse_gedcom"
path = "src/bin.rs"
